repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.sql
      - id: check-yaml
        args: ["--allow-multiple-documents"]
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.1
    hooks:
      - id: golangci-lint
        args: ["--config=.golangci.yml"]
        exclude: ^ui/
