repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.sql
      - id: check-yaml
        args: ["--allow-multiple-documents"]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.0
    hooks:
      - id: terraform_docs
      - id: terraform_tflint
      - id: terraform_fmt
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.59.0
    hooks:
      - id: golangci-lint
        args: ["--config=.golangci.yml"]
        exclude: ^ui/
  - repo: local
    hooks:
      - id: format
        name: format
        entry: /usr/bin/env bash -c 'make format'
        language: script
        files: \.(go)$
        description: "Checks files formatting with golines, openshift-goimports, gofumpt"
