version: '3'
services:
  postgres:
    container_name: awasm-postgres
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=dev-local-awasm-001
      - POSTGRES_PASSWORD=localdb
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "dev-local-awasm"]
      interval: 3s
      timeout: 3s
      retries: 5
volumes:
  data:
