global:
    # How frequently to scrape targets by default.
    scrape_interval: 30s
    # How long until a scrape request times out.
    scrape_timeout: 10s
    # How frequently to evaluate rules.
    evaluation_interval: 1m

rule_files:
    - "/etc/prometheus/alert.rules"

scrape_configs:
    - job_name: awasm
      scrape_interval: 5s
      metrics_path: 'metrics'
      static_configs:
        - targets: ["awasm:8080"]

    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "node-exporter"
      scrape_interval: 5s
      metrics_path: 'metrics'
      static_configs:
          - targets: ["node-exporter:9100"]
