server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: awasm
    static_configs:
      - targets:
          - localhost
        labels:
          job: awasm
          __path__: /var/log/awasm/*.log
    pipeline_stages:
      - json:
          expressions:
            type: "type"
            action: "action"
      - labels:
          type:
          action:
