ingress_url: http://0.0.0.0:8080

server:
  addr: 0.0.0.0:8080
  show_start_banner: true

db:
  host: postgres
  port: 5432
  user: "postgres"
  password: "localdb"
  schema: "dev-local-awasm-001"
  charset: "utf8mb4"
  log_sql: true
  ssl_mode: disable
  max_idle_conns: 100
  max_open_conns: 100
  conn_max_lifetime: 300

redis:
  host: redis
  port: 6379
  require_tls: false
  password:
  db: 1
  pool_size: 50

jwt:
  secret: lLTQ-5romlnVEOVdq6gCwEpCCKeypoKvuugm2GDfjzs=
  Exp: 86400

key:
  encryption: bASFEEq6OmFvrpYDGgsF7lZn95p8VkuDgPAw93hpad8=
  hash: lXdxDsEADpazx2V9vR6tjnDa60CVdEaIp2z8jLChTR0oyqpcWm0fQcDq7dKAzq44ttGcN90TvjmsC67llMsz8w==

logging:
  filename: ""
  level: "info"
  max_size: 100
  max_backups: 30
  max_age: 10
  use_local_time: false
  use_compress: true

i18n:
  bundle_dir: "./i18n"
