ingress_url: http://0.0.0.0:8080

server:
  addr: 0.0.0.0:8080
  show_start_banner: true

db:
  host: postgres
  port: 5432
  user: "awasm"
  password: "awasm"
  schema: "dev-local-awasm-001"
  charset: "utf8mb4"
  log_sql: true
  ssl_mode: disable
  max_idle_conns: 100
  max_open_conns: 100
  conn_max_lifetime: 300

redis:
  host: redis
  port: 6379
  require_tls: false
  password:
  db: 0
  pool_size: 50

jwt:
  secret: lLTQ-5romlnVEOVdq6gCwEpCCKeypoKvuugm2GDfjzs=
  Exp: 86400

key:
  encryption: bASFEEq6OmFvrpYDGgsF7lZn95p8VkuDgPAw93hpad8=
  hash: lXdxDsEADpazx2V9vR6tjnDa60CVdEaIp2z8jLChTR0oyqpcWm0fQcDq7dKAzq44ttGcN90TvjmsC67llMsz8w==
  api_key_signature_hmac: N3BGfY5GC9JNuWvjq2CADN7guXv_yHQETcRJtDFp2krcY8Z8IjKHxqMUHQoJZAWD_RTsjL72CkAw98P7JU7Vyw==
  api_key_database_hmac: 1cVQ7W1VtEl0guRH7fn710l52hJ-wGxGtKQZBQaNs0Md_tW5YBxWZh4iOxgOFMSu5f9aX12X_QZtoZqoGfL2YA==
  cache_key_hmac: zSJlncUERaTItwqwyWlvD3N662EVvEWBVP36uSerGILD7FGxUSFx6hH5x41kjPhbuHqc8T6eeGiAzmPm30qnMg==

smtp:
  from_email: support@awasm.com
  from_name: Local Awasm
  host: 127.0.0.1
  port: 1025
  user:
  password:

logging:
  filename: ""
  level: "info"
  max_size: 100
  max_backups: 30
  max_age: 10
  use_local_time: false
  use_compress: true

session:
  timebox: "720h"
  inactivity_timeout: "72h"

security:
  refresh_token_reuse_interval: 0

i18n:
  bundle_dir: "./i18n"
