server:
  http:
    addr: 0.0.0.0:3000

db:
  host: 127.0.0.1
  port: 5432
  user: "postgres"
  password: "localdb"
  schema: "test-local-awasm-001"
  charset: "utf8mb4"
  log_sql: false
  ssl_mode: disable
  max_idle_conns: 1000
  max_open_conns: 100
  conn_max_lifetime: 300

key:
  encryption: kUbSxDDI/zFES4GW/HM5FB8ue9qdBwrzi6PJ75ZeOO0=
  hash: 0P04lPYQDfBGQn+ehhZFnbBup8iNT8a3WyPl8uL74yAGbJtdDA88Detti6DcDA+b5wefXzmwmlXV1hfUWvn0Rw==

i18n:
  bundle_dir: "./i18n"
