server:
  http:
    addr: 0.0.0.0:3000

db:
  host: 127.0.0.1
  port: 5432
  user: "postgres"
  password: "localdb"
  schema: "dev-local-awasm-001"
  charset: "utf8mb4"
  log_sql: true
  ssl_mode: disable
  max_idle_conns: 1000
  max_open_conns: 100
  conn_max_lifetime: 300

key:
  encryption: bASFEEq6OmFvrpYDGgsF7lZn95p8VkuDgPAw93hpad8=
  hash: lXdxDsEADpazx2V9vR6tjnDa60CVdEaIp2z8jLChTR0oyqpcWm0fQcDq7dKAzq44ttGcN90TvjmsC67llMsz8w==

i18n:
  bundle_dir: "./i18n"
