server:
  http:
    addr: 127.0.0.1:3000

db:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "toor"
  schema: "dev-local-awasm-001"
  charset: "utf8mb4"
  log_sql: true
  sll_mode: false
  max_idle_conns: 1000
  max_open_conns: 100
  conn_max_lifetime: 300
