version: "3.8"

services:
  awasm:
    build:
      context: ./../..
    ports:
      - 8080:8080 # API
      - 2112:2112 # Prometheus metrics
    environment:
      - TZ=UTC
    depends_on:
      - postgres
    networks:
      - awasm-network

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=awasm
      - POSTGRES_PASSWORD=awasm
      - POSTGRES_DB=dev-local-awasm-001
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "dev-local-awasm-001",
          "-U",
          "awasm",
        ]
      interval: 1s
      timeout: 5s
      retries: 20
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - awasm-network

  redis:
    image: redis:6.2.5
    ports:
      - 6379:6379
    environment:
      - TZ=UTC
    volumes:
      - redis-data:/data:rw
    networks:
      - awasm-network

  smtp:
    image: lytrax/mailhog:latest # https://github.com/mailhog/MailHog/issues/353#issuecomment-821137362
    restart: always
    logging:
      driver: "none" # disable saving logs
    ports:
      - 1025:1025 # SMTP server
      - 8025:8025 # Web UI
    networks:
      - awasm-network

volumes:
  postgres-data:
  redis-data:

networks:
  awasm-network:
