name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Build
        run: make build

      - name: Test
        run: make test
        env:
          PWD: ${{ github.workspace }}

      - name: Install dependencies
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.2

      - name: Run linter
        run: make lint

      - name: Telegram notification
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            *${{ github.actor }}* created commit:
            `Commit message`: *${{ github.event.commits[0].message }}*
            `Repository`: *${{ github.repository }}*

            *${{github.repository}}* - a *${{ github.event_name }}* to *${{ github.ref }}* triggered by ${{ github.actor }} has status *${{ job.status }}* ${{ job.status == 'success' && '&#9989;' || '&#10060;' }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
